/* eslint-disable @typescript-eslint/no-require-imports */
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
function load(file,deps={}){const js=ts.transpileModule(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const exports={};new Function('exports','require',js)(exports,name=>deps[name]??require(name));return exports;}
const n=load('app/lib/nutrition.ts'),r=load('app/lib/records.ts',{'./nutrition':n});
const amount=(carbs=100)=>({carbs,protein:20,fat:10,vitaminC:30,calcium:200});
test('actual consumed fraction is applied once, across meals and snacks',()=>{const day=r.emptyDay('2026-10-09');day.breakfast={...day.breakfast,analysis:{foods:[],message:'',estimatedNutrition:amount()},portion:0.5};day.lunch={...day.lunch,nutrition:amount(50),portion:1};day.snacks=[{id:'s',note:'お茶',date:day.date,nutrition:amount(10),portion:1}];const t=n.dailyNutrition(day);assert.equal(t.carbs.total,110);assert.equal(t.protein.total,50);assert.equal(t.calcium.total,500);assert.equal(t.carbs.known,3);assert.equal(t.carbs.missing,0);});
test('manual correction overrides AI without double-counting',()=>{const day=r.emptyDay('2026-10-09');day.breakfast={...day.breakfast,analysis:{foods:[],message:'',estimatedNutrition:amount(100)},nutrition:amount(40),portion:0.5};assert.equal(n.dailyNutrition(day).carbs.total,20);});
test('unknown values and unanalysed snacks are flagged instead of filled with zero',()=>{const day=r.emptyDay('2026-10-09');day.breakfast={...day.breakfast,nutrition:amount(50)};day.lunch={...day.lunch,note:'昼食',nutrition:{...amount(10),calcium:null}};day.snacks=[{id:'s',note:'おやつ',date:day.date}];assert.equal(n.dailyNutrition(day).calcium.total,200);assert.equal(n.dailyNutrition(day).calcium.missing,2);assert.equal(n.dailyNutrition(day).carbs.missing,1);});
test('no data is uncalculated, while confirmed zero intake is valid',()=>{const day=r.emptyDay('2026-10-09');assert.equal(n.dailyNutrition(day).carbs.known,0);day.breakfast={...day.breakfast,note:'食べていない',portion:0};assert.equal(n.dailyNutrition(day).carbs.known,1);assert.equal(n.dailyNutrition(day).carbs.total,0);});
test('totals are computed afresh so removing a meal or changing day cannot retain old amounts',()=>{const day=r.emptyDay('2026-10-09');day.breakfast={...day.breakfast,nutrition:amount()};assert.equal(n.dailyNutrition(day).carbs.total,100);day.breakfast=r.emptyMeal();assert.equal(n.dailyNutrition(day).carbs.total,0);assert.equal(n.dailyNutrition(r.emptyDay('2026-10-08')).carbs.known,0);});
test('missing and zero goals produce no percentage; values above goal retain their true percentage',()=>{assert.equal(n.goalProgress(100,undefined),null);assert.equal(n.goalProgress(100,0),null);assert.deepEqual(n.goalProgress(150,100),{percent:150,width:100});assert.deepEqual(n.goalProgress(25,100),{percent:25,width:25});});
test('numeric data rejects invalid values and goals require positive values',()=>{assert.equal(n.parseNutrition({carbs:-1}),null);assert.equal(n.parseNutrition({carbs:Infinity}),null);assert.equal(n.parseNutrition({carbs:'10'}),null);assert.equal(n.parseNutrition([]),null);assert.deepEqual(n.parseGoals({carbs:0,protein:60}),{protein:60});});
test('estimates, manual corrections, portions and snack corrections survive save/reload',()=>{const analysis={foods:[],message:'',estimatedNutrition:amount(),portionNote:'一般的な一人前として推定'};const meal={...r.emptyMeal(),analysis,nutrition:amount(80),portion:0.75};assert.deepEqual(r.normalizeMeal(meal),{...meal,analyzed:true});const days=r.combineRecords('u',[{id:'u_d',data:{uid:'u',date:'2026-10-09',breakfast:meal,snacks:[{id:'s',date:'2026-10-09',note:'牛乳',nutrition:amount(10),portion:0.5}]}}],[],[],[]);assert.equal(n.dailyNutrition(days['2026-10-09']).carbs.total,65);assert.equal(r.hasRecord(days['2026-10-09']),true);assert.equal(r.parseAnalysis({...analysis,estimatedNutrition:{carbs:-1}}),null);});
